<a href="https://colab.research.google.com/github/Nil1205/PANDAS/blob/main/Assignment_1_Student_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [1]:
import numpy as np
import pandas as pd

#### 2. Create an array from my_list=[5,10,15,20,25]

In [2]:
my_list=[5,10,15,20,25]
np.array([5,10,15,20,25])

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [3]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [55]:
np.ones([4,4], dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [7]:
np.ones((4,4),dtype=int)*7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create same array above with full method

In [56]:
np.full((4,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [8]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [10]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [12]:
np.linspace(0,24,25,dtype=int).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 10. Create 5 random number with numpy

In [13]:
np.random.rand(5)

array([0.02734017, 0.63824833, 0.17393165, 0.52375511, 0.44803276])

#### 11. Create random normal distributed 5x5 array

In [14]:
np.random.randn(5,5)

array([[-0.14502737, -0.80357889,  0.2076553 ,  0.93431636,  0.90481168],
       [ 0.21572746,  0.21265255,  1.84998694,  1.41820643, -0.35481085],
       [-0.69883294, -0.72601014,  0.69055927, -1.03313427,  0.34746147],
       [ 0.96967277,  0.64221897,  0.75490347, -0.24891319,  1.67219913],
       [-0.37252891, -1.75671827,  0.74118213,  1.99896316,  0.71628859]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [16]:
np.random.randint(20,50,12).reshape(3,4)

array([[47, 44, 20, 40],
       [48, 48, 27, 20],
       [42, 45, 46, 33]])

#### 13. Reshape the array below with shape 6x8

In [18]:
ranarr=np.array([52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8, 44,  2, 46, 27, 11,
       29, 30, 26,  8, 49, 19,  2,  9, 38, 40, 36, 16, 41, 39, 17, 20, 42,
       23, 35, 45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52])
ranarr

array([52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8, 44,  2, 46, 27, 11,
       29, 30, 26,  8, 49, 19,  2,  9, 38, 40, 36, 16, 41, 39, 17, 20, 42,
       23, 35, 45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52])

In [19]:
ranarr.reshape(6,8)

array([[52, 48, 21, 29, 15, 35,  3, 29],
       [43, 48, 38,  8, 44,  2, 46, 27],
       [11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17],
       [20, 42, 23, 35, 45, 18, 40,  9],
       [36, 37,  5, 17, 44, 36,  2, 52]])

array([[52, 48, 21, 29, 15, 35,  3, 29],
       [43, 48, 38,  8, 44,  2, 46, 27],
       [11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17],
       [20, 42, 23, 35, 45, 18, 40,  9],
       [36, 37,  5, 17, 44, 36,  2, 52]])

In [20]:
#reshape with -1
ranarr.reshape(-1,8)

array([[52, 48, 21, 29, 15, 35,  3, 29],
       [43, 48, 38,  8, 44,  2, 46, 27],
       [11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17],
       [20, 42, 23, 35, 45, 18, 40,  9],
       [36, 37,  5, 17, 44, 36,  2, 52]])

## Numpy Indexing and Selection


In [23]:
#Create array below
mat=np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [24]:
mat[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [25]:
mat[::,0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [27]:
mat[1,::2]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [ ]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [29]:

mat[:,2]=77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [30]:
mat[[1,3],[0,1]]

array([ 5, 14])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [31]:
mat[1::2,::2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [ ]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [32]:
mat[mat<10]

array([1, 2, 4, 5, 6, 8, 9])

In [33]:
mat[mat>12]

array([77, 77, 77, 13, 14, 77, 16])

In [34]:
mat[mat<10]+mat[mat>12]

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [35]:
(mat[mat<10]+mat[mat>12]).std()

29.700546274093877

#### 22. Get the sum of second column from array above

In [ ]:
#print array here
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [37]:
mat[:,1].sum(axis=0)

32

#### 23. Get the median,mean and std of 3rd row from array above

In [39]:
mat=np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [40]:
mat[2]

array([ 9, 10, 11, 12])

In [42]:
#median
np.median(mat[2])

10.5

In [43]:
#mean
np.mean(mat[2])

10.5

In [44]:
#std
np.std(mat[2])

1.118033988749895

# Pandas Section

In [45]:
import pandas as pd

**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [52]:
sal=pd.read_csv('Salaries 2.csv')
sal

Id         EmployeeName  ...         Agency  Status
0            1       NATHANIEL FORD  ...  San Francisco     NaN
1            2         GARY JIMENEZ  ...  San Francisco     NaN
2            3       ALBERT PARDINI  ...  San Francisco     NaN
3            4    CHRISTOPHER CHONG  ...  San Francisco     NaN
4            5      PATRICK GARDNER  ...  San Francisco     NaN
...        ...                  ...  ...            ...     ...
116474  116475    Ramon R Dominguez  ...  San Francisco     NaN
116475  116476           Evan Mogan  ...  San Francisco     NaN
116476  116477       Denise R Green  ...  San Francisco     NaN
116477  116478  Richard F Archibald  ...  San Francisco     NaN
116478  116479   Justin P Dauterman  ...            NaN     NaN

[116479 rows x 13 columns]

In [57]:
sal.head()

Id       EmployeeName  ...         Agency  Status
0   1     NATHANIEL FORD  ...  San Francisco     NaN
1   2       GARY JIMENEZ  ...  San Francisco     NaN
2   3     ALBERT PARDINI  ...  San Francisco     NaN
3   4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4   5    PATRICK GARDNER  ...  San Francisco     NaN

[5 rows x 13 columns]

In [60]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116479 entries, 0 to 116478
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                116479 non-null  int64  
 1   EmployeeName      116479 non-null  object 
 2   JobTitle          116479 non-null  object 
 3   BasePay           115874 non-null  float64
 4   OvertimePay       116479 non-null  float64
 5   OtherPay          116479 non-null  float64
 6   Benefits          80320 non-null   float64
 7   TotalPay          116478 non-null  float64
 8   TotalPayBenefits  116478 non-null  float64
 9   Year              116478 non-null  float64
 10  Notes             0 non-null       float64
 11  Agency            116478 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(9), int64(1), object(3)
memory usage: 11.6+ MB


In [59]:
sal.describe()

Id        BasePay    OvertimePay  ...           Year  Notes  Status
count  116479.00000  115874.000000  116479.000000  ...  116478.000000    0.0     0.0
mean    58240.00000   69711.777605    5552.186954  ...    2012.114537    NaN     NaN
std     33624.73534   44304.895794   12366.738794  ...       0.907971    NaN     NaN
min         1.00000    -166.010000      -0.010000  ...    2011.000000    NaN     NaN
25%     29120.50000   38138.595000       0.000000  ...    2011.000000    NaN     NaN
50%     58240.00000   66624.240000       0.000000  ...    2012.000000    NaN     NaN
75%     87359.50000  100736.977500    5165.330000  ...    2013.000000    NaN     NaN
max    116479.00000  319275.010000  245131.880000  ...    2014.000000    NaN     NaN

[8 rows x 10 columns]

**How many different year value are there**

In [61]:
sal.Year.value_counts()

2013.0    37606
2012.0    36766
2011.0    36159
2014.0     5947
Name: Year, dtype: int64

**Print out max and avg Totalpay**

In [62]:
#max

sal.max()["TotalPay"]

567595.43

In [63]:
sal.TotalPay.mean()

78951.20378947901

**How many records are there which have TotalPay bigger than avg TotalPay**

In [68]:
len(sal.TotalPay[sal.TotalPay> sal.TotalPay.mean()].value_counts())



49464

**How much does ALBERT PARDINI make (including benefits)?**

In [72]:
sal.TotalPayBenefits[sal["EmployeeName"]=="ALBERT PARDINI"]

2    335279.91
Name: TotalPayBenefits, dtype: float64

**Who is lowest paid person**

In [75]:
sal[sal.TotalPayBenefits==sal.TotalPayBenefits.min()]["EmployeeName"]

110530    David P Kucia
Name: EmployeeName, dtype: object

**What are the unique Jobs in dataset?**

In [77]:
sal.JobTitle.unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ...,
       'Lieutenant (Police Department)', 'Deputy Sheriff (SFERS)',
       'Undersheriff (SFERS)'], dtype=object)

**List 3 least common Jobs**

In [86]:
salary["JobTitle"].value_counts(ascending=False).sort_values()[0:3]

NameError: ignored

**How many people earned more than avg in 2012**

In [78]:
Salary [(salary.TotalPayBenefits>salary.TotalPayBenefits.mean()) &(salary.Year==2012)]["EmployeeName"].count()

NameError: ignored

**How many people have the word Manager in their job title?**

In [ ]:
#use apply function here


4110

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [49]:
sal.head()

NameError: ignored

In [ ]:
sal_new=
sal_new

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [ ]:
sal_new=
sal_new

EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

         TotalPay  TotalPayBenefits  
0       567595.43         567595.43  
1       538909.28         538909.28  
2       335279.91         335279.91  
3       332343.61         332343.61  
4       326373.19         326373.19  
...           ...               ...  
148649       0.00              0.00  
148650       0.00              0.00  
148651       0.00              0.00  
148652       0.00              0.00  
148653    -618.13           -618.13  

[148654 rows x 4 columns]

**Print out the names of the employees who earn more than min, but less than avg**

10806            KWE LEE
10807     MIGUEL CARO JR
10808      JOANNE MORRIS
10809      LAYLA WELBORN
10810            LE BANH
               ...      
148648       Leon Walker
148649     Roy I Tillery
148650      Not provided
148651      Not provided
148652      Not provided
Name: EmployeeName, Length: 75649, dtype: object