<a href="https://colab.research.google.com/github/Nil1205/PANDAS/blob/main/DAwPy_S3_(Pandas_Series)_benim_yapt%C4%B1%C4%9F%C4%B1m.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<h1><p style="text-align: center;">Pandas Lesson, Session - 3</p><h1>

# Pandas Series

In [1]:
import numpy as np
import pandas as pd

## Creating a Pandas Series

pd.Series(data=None, index=None, dtype=None, name=None, copy=False, fastpath=False)

One-dimensional ndarray with axis labels (including time series).

In [10]:
labels = ['a','b','c']
my_list = [10, 20, 30]
arr=np.array([my_list])
arr

array([[10, 20, 30]])

In [11]:
arr=np.array([10,20,30])
arr

array([10, 20, 30])

In [12]:
d={"a":10,"b":20,"c":30}
arr=np.array(d)
arr

array({'a': 10, 'b': 20, 'c': 30}, dtype=object)

In [13]:
arr=np.array({"a":10,"b":20,"c":30})
arr

array({'a': 10, 'b': 20, 'c': 30}, dtype=object)

### **Using Lists**

In [14]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [15]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [16]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [17]:
pd.Series([10,20,30])

0    10
1    20
2    30
dtype: int64

### **Using NumPy Arrays**

In [19]:
arr

array({'a': 10, 'b': 20, 'c': 30}, dtype=object)

In [21]:
pd.Series(data = arr, index = labels)

a    {'a': 10, 'b': 20, 'c': 30}
b    {'a': 10, 'b': 20, 'c': 30}
c    {'a': 10, 'b': 20, 'c': 30}
dtype: object

### **Using Dictionary**

In [22]:
e={"v":"ayşe","a":"mehmet","b":"beril"}
pd.Series(e)

v      ayşe
a    mehmet
b     beril
dtype: object

In [24]:
pd.Series(data=e, index=["g","a","m"])

g       NaN
a    mehmet
m       NaN
dtype: object

In [25]:
pd.Series(data=d, index=["k","b","m"])

k     NaN
b    20.0
m     NaN
dtype: float64

### Using Scalar Value

In [26]:
pd.Series(data="Steve")

0    Steve
dtype: object

In [29]:
pd.Series(["neslihan","erdem","asya","kerem"])

0    neslihan
1       erdem
2        asya
3       kerem
dtype: object

In [32]:
pd.Series(data="erdem", index=range(1,4))

1    erdem
2    erdem
3    erdem
dtype: object

In [34]:
pd.Series(data="neslihan", index=["d","e","h"])

d    neslihan
e    neslihan
h    neslihan
dtype: object

### Data in a Series

A pandas Series can hold a variety of object types:

{} or set()

In [36]:
set1=(1,2,3,6)

In [37]:
pd.Series(set1)

0    1
1    2
2    3
3    6
dtype: int64

In [39]:
pd.Series([sum, list, len])[1]([1,3,4,5])

[1, 3, 4, 5]

In [43]:
pd.Series([sum, len, list])[1]([1,4,5,7,3])

5

In [45]:
pd.Series([sum, len, set])[2]([1,4,5,7,3])

{1, 3, 4, 5, 7}

In [48]:
pd.Series([sum, print, set])[2]("nessslihan")

{'a', 'e', 'h', 'i', 'l', 'n', 's'}

In [49]:
pd.Series([sum, len, print])[1]("clarusway")

9

In [52]:
mix_data=["aziz",2, True]
ser=pd.Series(mix_data)

In [53]:
type(ser)

pandas.core.series.Series

In [54]:
ser.dtype

dtype('O')

In [55]:
type(ser[1])

int

In [56]:
type(ser[0])

str

In [61]:
arr1=np.array([mix_data])
arr1

array([['aziz', '2', 'True']], dtype='<U4')

In [62]:
type(arr1)

numpy.ndarray

In [59]:
arr=pd.Series(mix_data)
arr

0    aziz
1       2
2    True
dtype: object

### Basic Attributes of Series

In [63]:
ser=pd.Series(np.random.randint(1,100,7))
ser

0    92
1    25
2    51
3    45
4    63
5    75
6     7
dtype: int64

In [64]:
type(ser)

pandas.core.series.Series

In [65]:
ser.dtype

dtype('int64')

In [66]:
ser.shape

(7,)

In [67]:
ser.size

7

In [68]:
ser.ndim

1

In [69]:
len(ser)

7

In [70]:
ser

0    92
1    25
2    51
3    45
4    63
5    75
6     7
dtype: int64

In [73]:
ser.index

RangeIndex(start=0, stop=7, step=1)

In [74]:
list(ser.index)

[0, 1, 2, 3, 4, 5, 6]

In [75]:
for i in ser.index:
  print(i)

0
1
2
3
4
5
6


In [80]:
ser.keys()

RangeIndex(start=0, stop=7, step=1)

In [81]:
ser.index

RangeIndex(start=0, stop=7, step=1)

In [82]:
ser.values

array([92, 25, 51, 45, 63, 75,  7])

In [83]:
[i for i in ser.values]

[92, 25, 51, 45, 63, 75, 7]

In [85]:
[i for i in ser.keys()]

[0, 1, 2, 3, 4, 5, 6]

In [86]:
ser.items

<bound method Series.items of 0    92
1    25
2    51
3    45
4    63
5    75
6     7
dtype: int64>

In [89]:
list(ser.items())

[(0, 92), (1, 25), (2, 51), (3, 45), (4, 63), (5, 75), (6, 7)]

In [92]:
for index, values in ser.items():
  print(f"index {index}, values {values}")


index 0, values 92
index 1, values 25
index 2, values 51
index 3, values 45
index 4, values 63
index 5, values 75
index 6, values 7


In [93]:
ser=pd.Series(data=np.random.randint(0,25,10), index=[i for i in "cheadhkllm"])
ser

c     8
h    21
e    14
a    20
d     8
h    11
k    13
l    21
l    13
m    14
dtype: int64

In [94]:
ser.head(3)

c     8
h    21
e    14
dtype: int64

In [95]:
ser.tail(4)

k    13
l    21
l    13
m    14
dtype: int64

In [97]:
ser.sample()

h    21
dtype: int64

In [99]:
ser.sort_values(ascending=True)

c     8
d     8
h    11
k    13
l    13
e    14
m    14
a    20
h    21
l    21
dtype: int64

In [102]:
ser.sort_index(ascending=True)

a    20
c     8
d     8
e    14
h    21
h    11
k    13
l    21
l    13
m    14
dtype: int64

In [103]:
ser

c     8
h    21
e    14
a    20
d     8
h    11
k    13
l    21
l    13
m    14
dtype: int64

In [104]:
ser.isin([5,9])

c    False
h    False
e    False
a    False
d    False
h    False
k    False
l    False
l    False
m    False
dtype: bool

In [105]:
ser.isin([3,8])

c     True
h    False
e    False
a    False
d     True
h    False
k    False
l    False
l    False
m    False
dtype: bool

In [109]:
a=pd.Series([i for i in "clarusway"])

In [111]:
a.isin(["a"])

0    False
1    False
2     True
3    False
4    False
5    False
6    False
7     True
8    False
dtype: bool

## Indexing Pandas Series

The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look up of information.

Let's see some examples of how to grab information from a Series. Let us create two sereis, ser1 and ser2:

In [115]:
ser1=pd.Series(data=[1,2,3,4], index=["usa","germany", "belgium","japan"])
ser1

usa        1
germany    2
belgium    3
japan      4
dtype: int64

In [119]:
ser2=pd.Series([1,2,5,4], index=["usa","germany","italy","japan"])
ser2

usa        1
germany    2
italy      5
japan      4
dtype: int64

In [120]:
ser1+ser2

belgium    NaN
germany    4.0
italy      NaN
japan      8.0
usa        2.0
dtype: float64

In [124]:
ser.sort_values

<bound method Series.sort_values of c     8
h    21
e    14
a    20
d     8
h    11
k    13
l    21
l    13
m    14
dtype: int64>

In [128]:
ser.sort_index

<bound method Series.sort_index of c     8
h    21
e    14
a    20
d     8
h    11
k    13
l    21
l    13
m    14
dtype: int64>

In [127]:
ser.sort_values()

c     8
d     8
h    11
k    13
l    13
e    14
m    14
a    20
h    21
l    21
dtype: int64

In [129]:
ser1["germany"]

2

In [133]:
ser2.japan

4

In [134]:
ser2["japan"]

4

In [136]:
s3=ser1+ser2
s3

belgium    NaN
germany    4.0
italy      NaN
japan      8.0
usa        2.0
dtype: float64

In [138]:
ser4=pd.Series(data=["a","b","h","l"])
ser4

0    a
1    b
2    h
3    l
dtype: object

In [140]:
ser4[2]

'h'

In [142]:
ser4[1:]

1    b
2    h
3    l
dtype: object

In [143]:
ser4[::-1]

3    l
2    h
1    b
0    a
dtype: object

Operations are then also done based off of index:

### pandas_series[index] | pandas_series[[indices, indices...]]

In [144]:
panser=pd.Series(data=[121,200,150,99],index=["terry","michael","orion","jason"])
panser

terry      121
michael    200
orion      150
jason       99
dtype: int64

In [146]:
panser.sort_values(ascending=True)

jason       99
terry      121
orion      150
michael    200
dtype: int64

In [147]:
panser.sort_index(ascending=True)

jason       99
michael    200
orion      150
terry      121
dtype: int64

In [148]:
panser[2]

150

In [149]:
panser[:2]

terry      121
michael    200
dtype: int64

In [150]:
panser["terry"]

121

In [160]:
panser = pd.Series(data = [121, 200, 150, 99], index = ["terry", "micheal", "orion", "jason"])
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [161]:
panser["terry":"orion"]


terry      121
micheal    200
orion      150
dtype: int64

In [162]:
index1 = ['terry', 'micheal', 'jason']
panser[index1]

terry      121
micheal    200
jason       99
dtype: int64

In [163]:
panser[0:3]

terry      121
micheal    200
orion      150
dtype: int64

### Recap for Several Selecting Attributes

In [164]:
panser.keys()

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [165]:
panser.index

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [167]:
panser.values

array([121, 200, 150,  99])

In [168]:
panser.items()

In [170]:
list(panser.items())

[('terry', 121), ('micheal', 200), ('orion', 150), ('jason', 99)]

In [171]:
for index, values in panser.items():
  print(index, values)

terry 121
micheal 200
orion 150
jason 99


In [172]:
"terry" in panser.index

True

In [173]:
"terry" in panser

True

In [175]:
200 in panser.values

True

In [176]:
55 in panser.values

False

In [178]:
panser[panser.values<100]

jason    99
dtype: int64

In [179]:
panser[panser<100]

jason    99
dtype: int64

In [181]:
panser[panser<100]=100
panser

terry      121
micheal    200
orion      150
jason      100
dtype: int64