<a href="https://colab.research.google.com/github/Nil1205/PANDAS/blob/main/genel_tekrar(pandas(3%2C4).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd

In [5]:
labels = ['a','b','c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {'a': 10, 'b': 20, 'c': 30}

In [6]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [7]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series([10, 20, 30])

0    10
1    20
2    30
dtype: int64

In [9]:
arr=np.array({'a': 10, 'b': 20, 'c': 30})
arr

array({'a': 10, 'b': 20, 'c': 30}, dtype=object)

In [10]:
arr


array({'a': 10, 'b': 20, 'c': 30}, dtype=object)

In [11]:
pd.Series(data=arr, index=labels)

a    {'a': 10, 'b': 20, 'c': 30}
b    {'a': 10, 'b': 20, 'c': 30}
c    {'a': 10, 'b': 20, 'c': 30}
dtype: object

In [12]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [13]:
pd.Series(data=d, index=["a","b","n"])

a    10.0
b    20.0
n     NaN
dtype: float64

In [14]:
pd.Series(data="nesli")

0    nesli
dtype: object

In [15]:
pd.Series(data="nesli", index=range(2,5))

2    nesli
3    nesli
4    nesli
dtype: object

In [16]:
pd.Series(data=10, index=["a","b","c"])

a    10
b    10
c    10
dtype: int64

In [17]:
set1 = (1,2,3,6)

In [18]:
pd.Series(set1)

0    1
1    2
2    3
3    6
dtype: int64

In [19]:
pd.Series([set,list,dict,sum,len])[3]([12,3,4])

19

In [20]:
pd.Series([set,list,dict,sum,len])[4]([12,3,4])

3

In [21]:
pd.Series([set,list,dict,sum,len,print])[5](["12,3,4"])

['12,3,4']


In [22]:
mix_data=["aziz", 2, True]
ser=pd.Series(mix_data)
ser

0    aziz
1       2
2    True
dtype: object

In [23]:
type(ser)

pandas.core.series.Series

In [24]:
type((ser)[1])

int

In [25]:
ser.dtype

dtype('O')

In [26]:
pandas=pd.Series(mix_data)
pandas

0    aziz
1       2
2    True
dtype: object

In [27]:
numpy=np.array(mix_data)
numpy

array(['aziz', '2', 'True'], dtype='<U4')

In [28]:
serr=pd.Series(np.random.randint(0,100,7))
serr

0    80
1    37
2    77
3    14
4    13
5    66
6    53
dtype: int64

In [29]:
type(serr)

pandas.core.series.Series

In [30]:
serr.shape

(7,)

In [31]:
len(serr)

7

In [32]:
ser.ndim

1

In [33]:
serr.index

RangeIndex(start=0, stop=7, step=1)

In [34]:
list(serr.index)

[0, 1, 2, 3, 4, 5, 6]

In [35]:
for i in serr.index:
  print(i)

0
1
2
3
4
5
6


In [36]:
serr.keys()

RangeIndex(start=0, stop=7, step=1)

In [37]:
serr.values

array([80, 37, 77, 14, 13, 66, 53])

In [38]:
[i for i in serr.values]

[80, 37, 77, 14, 13, 66, 53]

In [39]:
serr.items()

In [40]:
for i in serr.items():
  print(i)

(0, 80)
(1, 37)
(2, 77)
(3, 14)
(4, 13)
(5, 66)
(6, 53)


In [41]:
ser1=pd.Series(data=np.random.randint(0,25,10), index=[i for i in "cbaefdgihj"])
ser1

c    11
b    19
a     8
e    21
f     6
d    17
g     1
i    22
h     0
j    24
dtype: int64

In [42]:
ser1.head(3)

c    11
b    19
a     8
dtype: int64

In [43]:
ser1.tail(3)

i    22
h     0
j    24
dtype: int64

In [44]:
ser1.sample(2)

g    1
a    8
dtype: int64

In [45]:
ser1.sort_index(ascending=True)

a     8
b    19
c    11
d    17
e    21
f     6
g     1
h     0
i    22
j    24
dtype: int64

In [46]:
ser1.sort_values(ascending=True)

h     0
g     1
f     6
a     8
c    11
d    17
b    19
e    21
i    22
j    24
dtype: int64

In [47]:
ser1

c    11
b    19
a     8
e    21
f     6
d    17
g     1
i    22
h     0
j    24
dtype: int64

In [48]:
ser1.isin([18,9])

c    False
b    False
a    False
e    False
f    False
d    False
g    False
i    False
h    False
j    False
dtype: bool

In [49]:
new=pd.Series(data=[i for i in "clarusway"], index=range(9))
new

0    c
1    l
2    a
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

In [50]:
pd.Series([i for i in "clarusway"])

0    c
1    l
2    a
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

In [51]:
ser1=pd.Series([1,2,3,4], index= ["usa", "Germany", "Ussr", "tukrer"])
ser1

usa        1
Germany    2
Ussr       3
tukrer     4
dtype: int64

In [52]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])                      
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])

In [53]:
ser1+ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [54]:
ser3=pd.Series( ["a","b", "c", "d"])
ser3

0    a
1    b
2    c
3    d
dtype: object

In [55]:
ser3[0]

'a'

In [56]:
ser3[2]

'c'

In [57]:
ser3[2:]

2    c
3    d
dtype: object

In [58]:
ser3[:3]

0    a
1    b
2    c
dtype: object

In [59]:
ser3[:2]

0    a
1    b
dtype: object

In [60]:
panser = pd.Series(data = [121, 200, 150, 99], index = ["terry", "micheal", "orion", "jason"])
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [61]:
panser["terry"]

121

In [62]:
panser[:2]

terry      121
micheal    200
dtype: int64

In [63]:
panser[::-1]

jason       99
orion      150
micheal    200
terry      121
dtype: int64

In [64]:
panser[2]

150

In [65]:
panser["orion"]

150

In [66]:
panser[0]

121

In [67]:
panser.index

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [68]:
panser.keys

<bound method Series.keys of terry      121
micheal    200
orion      150
jason       99
dtype: int64>

In [69]:
index1 = ['terry', 'micheal', 'jason']

In [70]:
panser[index1]

terry      121
micheal    200
jason       99
dtype: int64

In [71]:
panser["terry":"orion"]

terry      121
micheal    200
orion      150
dtype: int64

In [72]:
panser.keys()

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [73]:
panser.index

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [74]:
panser.values

array([121, 200, 150,  99])

In [75]:
panser.items()

In [76]:
for i in panser.items():
  print(i)

('terry', 121)
('micheal', 200)
('orion', 150)
('jason', 99)


In [77]:
"orion" in panser

True

In [78]:
"terry" in panser.keys()

True

In [79]:
panser.isin([200,150])

terry      False
micheal     True
orion       True
jason      False
dtype: bool

In [80]:
panser[panser<100]

jason    99
dtype: int64

In [81]:
panser[panser>50]

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [82]:
panser[panser>100]=134
panser

terry      134
micheal    134
orion      134
jason       99
dtype: int64

In [83]:
data = [1, 3, 5, 7, 9, 18]

In [84]:
pd.DataFrame(data)

0
0   1
1   3
2   5
3   7
4   9
5  18

In [85]:
pd.Series(data)

0     1
1     3
2     5
3     7
4     9
5    18
dtype: int64

In [86]:
pd.DataFrame(data, columns=["columns1"])

columns1
0         1
1         3
2         5
3         7
4         9
5        18

In [87]:
m=np.arange(1,24,2).reshape(3,4)
m

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [88]:
df=pd.DataFrame(np.arange(1,24,2).reshape(3,4), columns=["var1", "var2", "var3", "var4"])
df

var1  var2  var3  var4
0     1     3     5     7
1     9    11    13    15
2    17    19    21    23

In [89]:
df.head(2)

var1  var2  var3  var4
0     1     3     5     7
1     9    11    13    15

In [90]:
df.columns

Index(['var1', 'var2', 'var3', 'var4'], dtype='object')

In [91]:
ser.index

RangeIndex(start=0, stop=3, step=1)

In [92]:
df.columns=["new1","new2", "new3", "new4"]
df

new1  new2  new3  new4
0     1     3     5     7
1     9    11    13    15
2    17    19    21    23

In [93]:
df.index=["a","b","c"]
df

new1  new2  new3  new4
a     1     3     5     7
b     9    11    13    15
c    17    19    21    23

In [94]:
df.rename(columns=({"new3":"x","new4":"y"}))

new1  new2   x   y
a     1     3   5   7
b     9    11  13  15
c    17    19  21  23

In [95]:
df.rename(index=({"a":"1","b":"2"}))

new1  new2  new3  new4
1     1     3     5     7
2     9    11    13    15
c    17    19    21    23

In [96]:
df.shape

(3, 4)

In [97]:
df.shape[1]

4

In [98]:
df.ndim

2

In [99]:
df.size

12

In [100]:
len(df)

3

In [101]:
df.values

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [102]:
type(df)

pandas.core.frame.DataFrame

In [103]:
type(df.values)

numpy.ndarray

In [104]:
type(df)

pandas.core.frame.DataFrame

In [105]:
type(df.keys)

method

In [106]:
s1 = np.random.randint(2,10, size = 4)
s2 = np.random.randint(3,10, size = 4)
s3= np.random.randint(4,15, size=4)

In [107]:
s4=np.random.randint(2,10, size=4).reshape(2,2)
s4

array([[3, 5],
       [6, 4]])

In [108]:
s5=np.arange(1,17).reshape(4,4)
s5

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [109]:
my_dict={"a":s1,"b":s2,"c":s3}
df1=pd.DataFrame(my_dict)
df1

a  b   c
0  2  3  11
1  4  9   7
2  4  3   4
3  6  3  14

In [110]:
df1.index

RangeIndex(start=0, stop=4, step=1)

In [111]:
for i in df1.index:
  print(i)

0
1
2
3


In [112]:
[i for i in df1.index]

[0, 1, 2, 3]

In [113]:
"var2" in df1

False

In [114]:
"a" in df1

True

In [115]:
from numpy.random import randn

In [116]:
np.random.seed(101)
df3=pd.DataFrame(randn(5,4), index="A B C D E".split(), columns="W X Y Z".split())
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [117]:
df3[["Y"]]

Y
A  0.907969
B -0.848077
C  0.528813
D -0.933237
E  2.605967

In [118]:
np.random.rand(3,4)

array([[0.73481906, 0.54196177, 0.91315356, 0.80792015],
       [0.40299783, 0.35722434, 0.95287671, 0.34363158],
       [0.86509982, 0.83027771, 0.53816145, 0.92246937]])

In [119]:
df3["Y"]

A    0.907969
B   -0.848077
C    0.528813
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [120]:
type(df3["Y"])

pandas.core.series.Series

In [121]:
df3[["Z","X"]]

Z         X
A  0.503826  0.628133
B  0.605965 -0.319318
C -0.589001  0.740122
D  0.955057 -0.758872
E  0.683509  1.978757

In [122]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [123]:
df3[["W","Z"]]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [124]:
df3["B":"D"]

W         X         Y         Z
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [125]:
df3[["X","Y"]]

X         Y
A  0.628133  0.907969
B -0.319318 -0.848077
C  0.740122  0.528813
D -0.758872 -0.933237
E  1.978757  2.605967

In [126]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [127]:
df3["A":"C"][["Y","Z"]]

Y         Z
A  0.907969  0.503826
B -0.848077  0.605965
C  0.528813 -0.589001

In [128]:
df3[["X","Z"]]["B":"E"]

X         Z
B -0.319318  0.605965
C  0.740122 -0.589001
D -0.758872  0.955057
E  1.978757  0.683509

In [129]:
df3["X*Y"]=df3["X"]*df3["Y"]
df3

W         X         Y         Z       X*Y
A  2.706850  0.628133  0.907969  0.503826  0.570325
B  0.651118 -0.319318 -0.848077  0.605965  0.270806
C -2.018168  0.740122  0.528813 -0.589001  0.391387
D  0.188695 -0.758872 -0.933237  0.955057  0.708208
E  0.190794  1.978757  2.605967  0.683509  5.156577

In [134]:
df3.drop("X*Y", axis=1)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [135]:
df3["T"]=[1,2,3,4,5]
df3

W         X         Y         Z       X*Y  T
A  2.706850  0.628133  0.907969  0.503826  0.570325  1
B  0.651118 -0.319318 -0.848077  0.605965  0.270806  2
C -2.018168  0.740122  0.528813 -0.589001  0.391387  3
D  0.188695 -0.758872 -0.933237  0.955057  0.708208  4
E  0.190794  1.978757  2.605967  0.683509  5.156577  5

In [138]:
df3["W+Z"]=df3["W"]+ df3["Z"]
df3

W         X         Y         Z       X*Y  T       W+Z
A  2.706850  0.628133  0.907969  0.503826  0.570325  1  3.210676
B  0.651118 -0.319318 -0.848077  0.605965  0.270806  2  1.257083
C -2.018168  0.740122  0.528813 -0.589001  0.391387  3 -2.607169
D  0.188695 -0.758872 -0.933237  0.955057  0.708208  4  1.143752
E  0.190794  1.978757  2.605967  0.683509  5.156577  5  0.874303

In [151]:
df3.drop("W+Z", axis=1)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [153]:
df3

W         X         Y         Z       W+Z
A  2.706850  0.628133  0.907969  0.503826  3.210676
B  0.651118 -0.319318 -0.848077  0.605965  1.257083
C -2.018168  0.740122  0.528813 -0.589001 -2.607169
D  0.188695 -0.758872 -0.933237  0.955057  1.143752
E  0.190794  1.978757  2.605967  0.683509  0.874303

In [155]:
df3.drop("W+Z", axis=1, inplace=True)

df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [148]:
df3.drop(columns=["X*Y", "T"], inplace=True)
df3

KeyError: ignored

In [157]:
df3.drop("C", axis=0)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [158]:
df3.drop(index=["A","B"])

W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [162]:
m=np.random.randint(1,40, size=(8,4))
df4=pd.DataFrame(m, columns=["var1","var2","var3","var4"], index=range(8))
df4

var1  var2  var3  var4
0     4    15    24    14
1    25    21     1    30
2    12    28    34    25
3    37    39    10     4
4     2    16     5     5
5    37    19    15    29
6    18    24    17     7
7     8    21    11    33

In [167]:
df4.loc[[3]]

var1  var2  var3  var4
3    37    39    10     4

In [173]:
df4.iloc[2:6,:]

var1  var2  var3  var4
2    12    28    34    25
3    37    39    10     4
4     2    16     5     5
5    37    19    15    29

In [174]:
df4.iloc[2:6]

var1  var2  var3  var4
2    12    28    34    25
3    37    39    10     4
4     2    16     5     5
5    37    19    15    29

In [176]:
df4.iloc[[2]]

var1  var2  var3  var4
2    12    28    34    25

In [178]:
df4.index="a b c d e f g h".split()
df4

var1  var2  var3  var4
a     4    15    24    14
b    25    21     1    30
c    12    28    34    25
d    37    39    10     4
e     2    16     5     5
f    37    19    15    29
g    18    24    17     7
h     8    21    11    33

In [179]:
df4.values

array([[ 4, 15, 24, 14],
       [25, 21,  1, 30],
       [12, 28, 34, 25],
       [37, 39, 10,  4],
       [ 2, 16,  5,  5],
       [37, 19, 15, 29],
       [18, 24, 17,  7],
       [ 8, 21, 11, 33]])

In [183]:
df4.iloc[1:4]

var1  var2  var3  var4
b    25    21     1    30
c    12    28    34    25
d    37    39    10     4

In [185]:
df4.loc[["c","d"]]

var1  var2  var3  var4
c    12    28    34    25
d    37    39    10     4

In [190]:
df4.loc["d":"g"]["var3"]

d    10
e     5
f    15
g    17
Name: var3, dtype: int64

In [191]:
df4.loc["d":"g"][["var3"]]

var3
d    10
e     5
f    15
g    17

In [192]:
df4.iloc[2:5,2]

c    34
d    10
e     5
Name: var3, dtype: int64

In [193]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [195]:
df3.loc[["C"]]

W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [197]:
df3.iloc[[2]]

W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [202]:
df3.iloc[:,[2]]

Y
A  0.907969
B -0.848077
C  0.528813
D -0.933237
E  2.605967

In [203]:
df3[["Y"]]

Y
A  0.907969
B -0.848077
C  0.528813
D -0.933237
E  2.605967

In [204]:
df3[["Y","X"]]

Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
C  0.528813  0.740122
D -0.933237 -0.758872
E  2.605967  1.978757

In [208]:
df3.loc[["C"],["Z"]]

Z
C -0.589001

In [209]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [211]:
df3.loc[["A","C"],["W","Z"]]

W         Z
A  2.706850  0.503826
C -2.018168 -0.589001

In [212]:
df3.iloc[[0,2],[0,3]]

W         Z
A  2.706850  0.503826
C -2.018168 -0.589001

In [213]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [214]:
df3[df3["Z"]>0.5]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [215]:
df3[["Z"]]

Z
A  0.503826
B  0.605965
C -0.589001
D  0.955057
E  0.683509

In [216]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [218]:
df3[df3["X"]<1][["W"]]

W
A  2.706850
B  0.651118
C -2.018168
D  0.188695

In [220]:
df3[df3["Y"]>0.5][["X"]]

X
A  0.628133
C  0.740122
E  1.978757

In [222]:
df3[df3["Y"]>0][["Z","W","Y"]]

Z         W         Y
A  0.503826  2.706850  0.907969
C -0.589001 -2.018168  0.528813
E  0.683509  0.190794  2.605967

In [230]:
df3[(df3["W"]>0) & (df3["Y"]<1)]=0
df3

W         X         Y         Z
A  0.000000  0.000000  0.000000  0.000000
B  0.000000  0.000000  0.000000  0.000000
C -2.018168  0.740122  0.528813 -0.589001
D  0.000000  0.000000  0.000000  0.000000
E  0.190794  1.978757  2.605967  0.683509

In [231]:
df3

W         X         Y         Z
A  0.000000  0.000000  0.000000  0.000000
B  0.000000  0.000000  0.000000  0.000000
C -2.018168  0.740122  0.528813 -0.589001
D  0.000000  0.000000  0.000000  0.000000
E  0.190794  1.978757  2.605967  0.683509

In [233]:
df3.loc[["C","E"],["X","Z"]]

X         Z
C  0.740122 -0.589001
E  1.978757  0.683509

In [248]:
df3.loc[((df3.W>1) | (df3.Y<1)), ['Y','Z']]


Y         Z
A  0.000000  0.000000
B  0.000000  0.000000
C  0.528813 -0.589001
D  0.000000  0.000000

In [ ]:
df3.loc[((df3.W)>1) |(df3.Y<1)),["Y","Z"]]

In [249]:
df3

W         X         Y         Z
A  0.000000  0.000000  0.000000  0.000000
B  0.000000  0.000000  0.000000  0.000000
C -2.018168  0.740122  0.528813 -0.589001
D  0.000000  0.000000  0.000000  0.000000
E  0.190794  1.978757  2.605967  0.683509

In [252]:
df3.reset_index(drop=True)

W         X         Y         Z
0  0.000000  0.000000  0.000000  0.000000
1  0.000000  0.000000  0.000000  0.000000
2 -2.018168  0.740122  0.528813 -0.589001
3  0.000000  0.000000  0.000000  0.000000
4  0.190794  1.978757  2.605967  0.683509

In [254]:
df3

W         X         Y         Z
A  0.000000  0.000000  0.000000  0.000000
B  0.000000  0.000000  0.000000  0.000000
C -2.018168  0.740122  0.528813 -0.589001
D  0.000000  0.000000  0.000000  0.000000
E  0.190794  1.978757  2.605967  0.683509

In [258]:
df3.index='A B C D E'.split()
df3

W         X         Y         Z
A  0.000000  0.000000  0.000000  0.000000
B  0.000000  0.000000  0.000000  0.000000
C -2.018168  0.740122  0.528813 -0.589001
D  0.000000  0.000000  0.000000  0.000000
E  0.190794  1.978757  2.605967  0.683509

In [268]:
df3["newidx"]='CA NY WY OR CO'.split()
df3

W         X         Y         Z newidx
A  0.000000  0.000000  0.000000  0.000000     CA
B  0.000000  0.000000  0.000000  0.000000     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.000000  0.000000  0.000000  0.000000     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [271]:
df3.drop("newidx", axis=1)

W         X         Y         Z
A  0.000000  0.000000  0.000000  0.000000
B  0.000000  0.000000  0.000000  0.000000
C -2.018168  0.740122  0.528813 -0.589001
D  0.000000  0.000000  0.000000  0.000000
E  0.190794  1.978757  2.605967  0.683509

In [272]:
df3.set_index("newidx")

W         X         Y         Z
newidx                                        
CA      0.000000  0.000000  0.000000  0.000000
NY      0.000000  0.000000  0.000000  0.000000
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.000000  0.000000  0.000000  0.000000
CO      0.190794  1.978757  2.605967  0.683509

In [273]:
newindx='CA NY WY OR CO'.split()
newindx

['CA', 'NY', 'WY', 'OR', 'CO']

In [276]:
df3["newindx"]=newindx
df3

W         X         Y         Z newidx newindx
A  0.000000  0.000000  0.000000  0.000000     CA      CA
B  0.000000  0.000000  0.000000  0.000000     NY      NY
C -2.018168  0.740122  0.528813 -0.589001     WY      WY
D  0.000000  0.000000  0.000000  0.000000     OR      OR
E  0.190794  1.978757  2.605967  0.683509     CO      CO

In [280]:
df3.set_index("Z")

W         X         Y newidx newindx
Z                                                     
 0.000000  0.000000  0.000000  0.000000     CA      CA
 0.000000  0.000000  0.000000  0.000000     NY      NY
-0.589001 -2.018168  0.740122  0.528813     WY      WY
 0.000000  0.000000  0.000000  0.000000     OR      OR
 0.683509  0.190794  1.978757  2.605967     CO      CO

In [283]:
outside = ['M1', 'M1', 'M1', 'M2', 'M2', 'M2','M3', 'M3', 'M3']
inside = [1, 2, 3, 1, 2, 3, 5, 6, 7]
multi_index=list(zip(outside, inside))
multi_index

[('M1', 1),
 ('M1', 2),
 ('M1', 3),
 ('M2', 1),
 ('M2', 2),
 ('M2', 3),
 ('M3', 5),
 ('M3', 6),
 ('M3', 7)]

In [285]:
hier_index=pd.MultiIndex.from_tuples(multi_index)
hier_index

MultiIndex([('M1', 1),
            ('M1', 2),
            ('M1', 3),
            ('M2', 1),
            ('M2', 2),
            ('M2', 3),
            ('M3', 5),
            ('M3', 6),
            ('M3', 7)],
           )

In [287]:
df=pd.DataFrame(np.random.randn(9,4), index=hier_index, columns=["A","B","C","D"])
df

A         B         C         D
M1 1  0.197524  2.302987  0.729024 -0.863091
   2  0.305632  0.243178  0.864165 -1.560931
   3 -0.251897 -0.578120  0.236996  0.200780
M2 1  0.327845  0.674485 -0.174057  0.780140
   2 -0.383258 -0.409318  0.343539  0.196275
   3 -0.982776  2.231555 -0.971393 -1.522333
M3 5  1.133703  0.528187  0.393461 -0.630507
   6 -1.398290 -0.219311 -0.045676  0.012421
   7  0.093628  1.240813 -1.097693 -1.908009

In [289]:
outside = ['M1', 'M1', 'M1', 'M2', 'M2', 'M2','M3', 'M3', 'M3']
inside = [1, 2, 3, 1, 2, 3, 5, 6, 7]
multi=list(zip(outside,inside))
multi

[('M1', 1),
 ('M1', 2),
 ('M1', 3),
 ('M2', 1),
 ('M2', 2),
 ('M2', 3),
 ('M3', 5),
 ('M3', 6),
 ('M3', 7)]

In [292]:
hier_index=pd.MultiIndex.from_tuples(multi)
df=pd.DataFrame(np.random.randn(9,4), index=hier_index, columns=["A","B","C","D"])
df

A         B         C         D
M1 1 -0.279510  1.062710  1.752014  0.695547
   2  0.153661  0.167638 -0.765930  0.962299
   3  0.902826 -0.537909 -1.549671  0.435253
M2 1  1.259904 -0.447898  0.266207  0.412580
   2  0.988773  0.513833 -0.928205  0.846904
   3 -0.298436  0.029141  0.889031 -1.839261
M3 5  0.863596 -1.076591 -0.580383  1.209027
   6  1.201744 -0.820463 -1.029577 -1.524856
   7 -0.854860  1.602816  0.185479 -0.994018

In [293]:
df.loc["M1"]

A         B         C         D
1 -0.279510  1.062710  1.752014  0.695547
2  0.153661  0.167638 -0.765930  0.962299
3  0.902826 -0.537909 -1.549671  0.435253

In [295]:
df.loc["M1"].loc[[2]]

A         B        C         D
2  0.153661  0.167638 -0.76593  0.962299

In [299]:
df.index.names = ['Group','Num']
df

A         B         C         D
Group Num                                        
M1    1   -0.279510  1.062710  1.752014  0.695547
      2    0.153661  0.167638 -0.765930  0.962299
      3    0.902826 -0.537909 -1.549671  0.435253
M2    1    1.259904 -0.447898  0.266207  0.412580
      2    0.988773  0.513833 -0.928205  0.846904
      3   -0.298436  0.029141  0.889031 -1.839261
M3    5    0.863596 -1.076591 -0.580383  1.209027
      6    1.201744 -0.820463 -1.029577 -1.524856
      7   -0.854860  1.602816  0.185479 -0.994018

In [300]:
df.xs("M1")

A         B         C         D
Num                                        
1   -0.279510  1.062710  1.752014  0.695547
2    0.153661  0.167638 -0.765930  0.962299
3    0.902826 -0.537909 -1.549671  0.435253

In [303]:
df.loc["M1"]

A         B         C         D
Num                                        
1   -0.279510  1.062710  1.752014  0.695547
2    0.153661  0.167638 -0.765930  0.962299
3    0.902826 -0.537909 -1.549671  0.435253

In [304]:
df.xs("M2")

A         B         C         D
Num                                        
1    1.259904 -0.447898  0.266207  0.412580
2    0.988773  0.513833 -0.928205  0.846904
3   -0.298436  0.029141  0.889031 -1.839261

In [307]:
df.xs(["M1",2], level=[0,1])

A         B        C         D
Group Num                                       
M1    2    0.153661  0.167638 -0.76593  0.962299

In [308]:
df

A         B         C         D
Group Num                                        
M1    1   -0.279510  1.062710  1.752014  0.695547
      2    0.153661  0.167638 -0.765930  0.962299
      3    0.902826 -0.537909 -1.549671  0.435253
M2    1    1.259904 -0.447898  0.266207  0.412580
      2    0.988773  0.513833 -0.928205  0.846904
      3   -0.298436  0.029141  0.889031 -1.839261
M3    5    0.863596 -1.076591 -0.580383  1.209027
      6    1.201744 -0.820463 -1.029577 -1.524856
      7   -0.854860  1.602816  0.185479 -0.994018

In [310]:
df.xs(("M1",2), level=[0,1])

A         B        C         D
Group Num                                       
M1    2    0.153661  0.167638 -0.76593  0.962299

In [312]:
df.xs(("M2",3),level=["Group","Num"])

A         B         C         D
Group Num                                        
M2    3   -0.298436  0.029141  0.889031 -1.839261

In [313]:
df.xs(5, level="Num")

A         B         C         D
Group                                        
M3     0.863596 -1.076591 -0.580383  1.209027

In [315]:
df.xs(7,level="Num")

A         B         C         D
Group                                       
M3    -0.85486  1.602816  0.185479 -0.994018

In [316]:
df.xs("M1", level="Group")

A         B         C         D
Num                                        
1   -0.279510  1.062710  1.752014  0.695547
2    0.153661  0.167638 -0.765930  0.962299
3    0.902826 -0.537909 -1.549671  0.435253

In [317]:
df.xs("M1")

A         B         C         D
Num                                        
1   -0.279510  1.062710  1.752014  0.695547
2    0.153661  0.167638 -0.765930  0.962299
3    0.902826 -0.537909 -1.549671  0.435253

In [318]:
df.xs("C", axis=1)

Group  Num
M1     1      1.752014
       2     -0.765930
       3     -1.549671
M2     1      0.266207
       2     -0.928205
       3      0.889031
M3     5     -0.580383
       6     -1.029577
       7      0.185479
Name: C, dtype: float64

In [320]:
import seaborn as sns

In [322]:
df=sns.load_dataset("iris")
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [323]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [325]:
df.shape

(150, 5)

In [326]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [327]:
df.sample(3)

sepal_length  sepal_width  petal_length  petal_width    species
109           7.2          3.6           6.1          2.5  virginica
140           6.7          3.1           5.6          2.4  virginica
39            5.1          3.4           1.5          0.2     setosa

In [328]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [329]:
df.describe().T

count      mean       std  min  25%   50%  75%  max
sepal_length  150.0  5.843333  0.828066  4.3  5.1  5.80  6.4  7.9
sepal_width   150.0  3.057333  0.435866  2.0  2.8  3.00  3.3  4.4
petal_length  150.0  3.758000  1.765298  1.0  1.6  4.35  5.1  6.9
petal_width   150.0  1.199333  0.762238  0.1  0.3  1.30  1.8  2.5

In [330]:
df.describe(include="all")

sepal_length  sepal_width  petal_length  petal_width species
count     150.000000   150.000000    150.000000   150.000000     150
unique           NaN          NaN           NaN          NaN       3
top              NaN          NaN           NaN          NaN  setosa
freq             NaN          NaN           NaN          NaN      50
mean        5.843333     3.057333      3.758000     1.199333     NaN
std         0.828066     0.435866      1.765298     0.762238     NaN
min         4.300000     2.000000      1.000000     0.100000     NaN
25%         5.100000     2.800000      1.600000     0.300000     NaN
50%         5.800000     3.000000      4.350000     1.300000     NaN
75%         6.400000     3.300000      5.100000     1.800000     NaN
max         7.900000     4.400000      6.900000     2.500000     NaN

In [331]:
df.corr()

sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.117570      0.871754     0.817941
sepal_width      -0.117570     1.000000     -0.428440    -0.366126
petal_length      0.871754    -0.428440      1.000000     0.962865
petal_width       0.817941    -0.366126      0.962865     1.000000

In [332]:
df.corr()[["sepal_length"]]

sepal_length
sepal_length      1.000000
sepal_width      -0.117570
petal_length      0.871754
petal_width       0.817941

In [337]:
df.corr().loc["petal_width","petal_length"]

0.9628654314027955

In [340]:
df["petal_length"].corr(df["petal_width"])

0.9628654314027961

In [342]:
df["species"].value_counts(dropna=False, normalize=True)

setosa        0.333333
virginica     0.333333
versicolor    0.333333
Name: species, dtype: float64

In [343]:
df.mean()

sepal_length    5.843333
sepal_width     3.057333
petal_length    3.758000
petal_width     1.199333
dtype: float64

In [344]:
df.sum(axis=0)

sepal_length                                                876.5
sepal_width                                                 458.6
petal_length                                                563.7
petal_width                                                 179.9
species         setosasetosasetosasetosasetosasetosasetosaseto...
dtype: object

In [345]:
df.sum(axis=1)

0      10.2
1       9.5
2       9.4
3       9.4
4      10.2
       ... 
145    17.2
146    15.7
147    16.7
148    17.3
149    15.8
Length: 150, dtype: float64

In [346]:
df["sepal_length"].sum()

876.5

In [347]:
df.sepal_length.sum()

876.5

In [348]:
df.species.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [350]:
df.species.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [353]:
df.loc[df["species"]=="setosa","sepal_length"]

0     5.1
1     4.9
2     4.7
3     4.6
4     5.0
5     5.4
6     4.6
7     5.0
8     4.4
9     4.9
10    5.4
11    4.8
12    4.8
13    4.3
14    5.8
15    5.7
16    5.4
17    5.1
18    5.7
19    5.1
20    5.4
21    5.1
22    4.6
23    5.1
24    4.8
25    5.0
26    5.0
27    5.2
28    5.2
29    4.7
30    4.8
31    5.4
32    5.2
33    5.5
34    4.9
35    5.0
36    5.5
37    4.9
38    4.4
39    5.1
40    5.0
41    4.5
42    4.4
43    5.0
44    5.1
45    4.8
46    5.1
47    4.6
48    5.3
49    5.0
Name: sepal_length, dtype: float64

In [361]:
df[(df.sepal_length>4) & (df.sepal_length<5)]

sepal_length  sepal_width  petal_length  petal_width     species
1             4.9          3.0           1.4          0.2      setosa
2             4.7          3.2           1.3          0.2      setosa
3             4.6          3.1           1.5          0.2      setosa
6             4.6          3.4           1.4          0.3      setosa
8             4.4          2.9           1.4          0.2      setosa
9             4.9          3.1           1.5          0.1      setosa
11            4.8          3.4           1.6          0.2      setosa
12            4.8          3.0           1.4          0.1      setosa
13            4.3          3.0           1.1          0.1      setosa
22            4.6          3.6           1.0          0.2      setosa
24            4.8          3.4           1.9          0.2      setosa
29            4.7          3.2           1.6          0.2      setosa
30            4.8          3.1           1.6          0.2      setosa
34            4.9          3.1           1.5          0.2      setosa
37            4.9          3.6           1.4          0.1      setosa
38            4.4          3.0           1.3          0.2      setosa
41            4.5          2.3           1.3          0.3      setosa
42            4.4          3.2           1.3          0.2      setosa
45            4.8          3.0           1.4          0.3      setosa
47            4.6          3.2           1.4          0.2      setosa
57            4.9          2.4           3.3          1.0  versicolor
106           4.9          2.5           4.5          1.7   virginica

In [364]:
df[(df.species == "virginica") & (df.sepal_length>4)  & (df.sepal_length<5)]



sepal_length  sepal_width  petal_length  petal_width    species
106           4.9          2.5           4.5          1.7  virginica

In [386]:
[df[df.sepal_length<5]==True]

[     sepal_length  sepal_width  petal_length  petal_width  species
 1           False        False         False        False    False
 2           False        False         False        False    False
 3           False        False         False        False    False
 6           False        False         False        False    False
 8           False        False         False        False    False
 9           False        False         False        False    False
 11          False        False         False        False    False
 12          False        False         False        False    False
 13          False        False         False        False    False
 22          False        False          True        False    False
 24          False        False         False        False    False
 29          False        False         False        False    False
 30          False        False         False        False    False
 34          False        False         False   

In [385]:
df.sort_values("sepal_length",ascending=True)

sepal_length  sepal_width  petal_length  petal_width    species
13            4.3          3.0           1.1          0.1     setosa
42            4.4          3.2           1.3          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
41            4.5          2.3           1.3          0.3     setosa
..            ...          ...           ...          ...        ...
122           7.7          2.8           6.7          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
117           7.7          3.8           6.7          2.2  virginica
135           7.7          3.0           6.1          2.3  virginica
131           7.9          3.8           6.4          2.0  virginica

[150 rows x 5 columns]